name: okoshki
description: 'Okoshki app'
publish_to: 'none'
version: 1.0.5+5
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0
  get_it: ^7.6.4
  json_annotation: ^4.8.1
  get_storage: ^2.1.1
  dio: ^5.3.4
  mask_text_input_formatter: ^2.6.0
  auto_route: ^7.8.4
  logger: ^2.0.2+1
  validators2: ^5.0.0
  group_button: ^5.3.3
  introduction_screen: ^3.1.12
  flutter_svg: ^2.0.9
  geolocator: ^10.1.0
  retrofit: ^4.0.3
  permission_handler: ^11.1.0
  image_picker: ^1.0.5
  image_cropper: ^5.0.1
  flutter_keyboard_visibility: ^5.4.1
  intl: ^0.18.1
  lottie: ^2.7.0
  path_provider: ^2.1.2
  flutter_cached_pdfview: ^0.4.2
  url_launcher: ^6.2.4
  provider: ^6.1.1
  flutter_rating_bar: ^4.0.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  device_info_plus: ^9.1.2
  flutter_native_splash: ^2.3.10
  firebase_core: ^2.25.4
  firebase_messaging: ^14.7.15
  android_id: ^0.3.6
  flutter_image_stack: ^0.0.7
  qr_flutter: ^4.1.0
  mobile_scanner: ^4.0.1
  easy_debounce: ^2.0.3
  flutter_map_location_marker: ^8.0.5
  flutter_map_marker_cluster: ^1.3.4
  flutter_countdown_timer: ^4.1.0
  collection: ^1.18.0
  map_launcher: ^3.1.0
  fluttertoast: ^8.2.4
  share_plus: ^7.2.2
  add_2_calendar: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  json_serializable: ^6.7.1
  auto_route_generator: ^7.3.2
  retrofit_generator: ^8.0.6
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/test.pdf
    - assets/logo/customer/
    - assets/logo/saloon/
    - assets/image/
    - assets/icons/

flutter_launcher_icons:
  android: true
  image_path_android: 'assets/icons/app-android.png'
  ios: true
  image_path_ios: 'assets/icons/app-ios.png'
  min_sdk_android: 21
  adaptive_icon_background: '#FF0000'

fonts:
  - family: SFProDisplay
    fonts:
      - asset: fonts/SF-Pro-Display-Regular.otf
        weight: 400
      - asset: fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: fonts/SF-Pro-Display-Bold.otf
        weight: 700